[package]
name = "load-pwp-tail"
version = "0.1.0"
authors = ["makr17 <bracher@gmail.com>"]

[dependencies]
chrono = "0.4"
postgres = { version = "0.19", features = ["with-chrono-0_4"] }
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
